version: '3'

services:
  api:
    build: .
    ports:
      - "8002:8000"
    environment:
      - INSTAGRAM_ACCESS_TOKEN=${INSTAGRAM_ACCESS_TOKEN}
    volumes:
      - .:/app
    restart: unless-stopped 